# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b0b567a0798200a2b7ef02e4812fe1cc7db92ec10377b1fecd8d9b08e6725b16c5b10e9c8da44a53b262039949be91f6671f606b688a7797d82ac811b5334f

test:
  secret_key_base: fbcc8f0f0bc62cbf771dd7c2e9df61a43ad73a3cc42bbafb4f87b9812159807a8e58e0da94bcf62a79e80c7298a49eb1b694b0de3f758284f4f4eb48dfca08ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
